update-checker: true

undisguise-at-death: true

undisguise-on-disconnection: false

right-click-remove-head: true

unkamoof-give-back-the-head: false

message:
  join: "§a✔ Vous êtes déguisé faites /unkamoof pour ne plus être déguisé"
  death: "§c❌ Vous n'êtes maitenant plus déguisé"
  already-disguised: "§c❌ Vous êtes déjà déguisé"
  not-disguised: "§c❌ Vous n'êtes pas déguisé"
  disguise: "§a✔ Vous étes maintenant déguisé faites /unkamoof pour ne plus être déguisé"
  undisguise: "§a✔ Vous n'êtes maitenant plus déguisé"