#  &&&&&&@&&&&&%%%%%%%%%%%&&&&&&&&&&%&&&%%#%&&&&%&%%&&&&&&&%#########%%&%%%%%%%%%%%
#  %%%%%%%%%%%#%%%%%%%%%&&&&&%##############%%#%%%#%#%%&&&&%#########%%%&&&%%&&&%%%
#  &@&&&&&&&%%%%%%%%%%%%%%%%#%%%%%####%/*,**(*,*,**#%%###################%%%%%%%%%%
#  &&&&&&&&@&&&&@&%%%%%%&&&&&&%%##%##%(//,,,,,*,.,,**(###%##############%&@&&&&@@&&
#  &&&&&&&@&&&@&%%%%&%%%&&&&@%&&%%&%%%#/((((//(((/**,*#&%&&%#######%%%&&&&&&&&&@&@&
#  &&&&&&&%%%%%%&&%%%%&&%%%%%%%%%###*/(((((#(######(**%######%#########%%%%%&&&&@@&
#  @&%%%%%%%%%&&@&%%%%&%%%%&&&&%%%#%#/#/(///(((#####**%%#####&#####%######%&&&&&&@&
#  %%%&@@&%%%&@@@&&&%%%%&@@@@@@@@&&/###(((//(#(((((((&&&&&#########%&%%#######%%&@&
#  %&&@&@&&&%&&@@&&&&%&&@@@@&@@@@&&#(%((((**/(#####/(%&&&&%&%######%%&%###%&&%##%%%
#  %%%&&&&%%%&%%&&%%%%%&@@@@&@&&&&&%&&((///((#####(#%%%%%&%%#######%&###%&%%&&%####
#  %%%%%%%%&@&@@&%%%%%%&@@&@&@&&&&&%&%#(((((####(%&&&%%%%%#%%%#######%%###%&&&%###%
#  %&&&&%%&@@&@@&%%%%%&%%%&@&@&&&%#%##///////((((##%&&&&%%##########%&%&&%#%%#%%#%%
#  &&&&&@%%&&&@@&%%%%&&&&%%%%%#%####%%(///(((###%/,*%&&&%####%%#####%&&&&&%&&&&&###
#  %%&&&&&%&&&&@%%%%%%%%%%%%%%####%##/(///(((/#%%,,,..,,*//(#%%#####%%%&&%%&&&&%&##
#  %%%&&&&%%&&&&%%%%%%%%%&%#(*,**(&%(//*///(%%%%*,,............,,,,#%%%%%#%&&&%####
#  &%#%&&&%%%%%%#%###%(/*,,.....,(###////#%%%%(,..................,,,%%%##&&&&###%%
#  %%%%%%%&&&&%%%%####,.........,*.*/*///###/,......................,%#%%###%###%&%
#  %####%%&&&&&&%%%##*.............*//***,*/(*.......................,(%%%#########
#  %#####%%&&&&%%####*,............(((((#(/*..........................%%%%%#####%%%
#  ##%%%###%&&&&%####*...............((#/((#...................... ....,%%######%&&
#  #%&%%###%&&&%%%###,.............//#(/. .....................  .......,,/%#%%##&&
#  #&&%%##%%#&&%%%###,.............*(#*((/*......,*(((((((.....   .. ......../%&#%&
#  &&%###%&&#%&%%####,.... ..........,/*/(/......**//////((*...   . ..........,,(##
#  %####%##%%%#%####%*.... .........,,/ .........../**///(((*..................,/##
#  #(%%%&&&%#%#######,,...   ......./(///* ..........  .*//(/,..................*##
#  %%%%%&%&&&%#######,*./,....,////,.,***/.......              ..................##
#  %#%%%&%%%%%######(/...(//***/**..***                       . ...............,##(
#  ((###%%%%#########(.*..,*******, .**// .                      *#(((/((#######%#(
#  ((##%%%###########((,....*,,,,*..,,*.. .          ..          .######((#####((((
#  ((((((((###(#(((((##(((*...    . .,*,.                  .......(((#(#((((##(((((
#  (#((((###%#((((((#####(((((/... ..,*.              . ..........,((((((((((((((((
#  (#((((######((((((####(((((,....****,                . .........((((((((((((((((


#Oui j'utilise la config pour faire un base de donnée et alors


db: